# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
 -group: Terraform-dev
 -name: data-fac-name
   value:'$(data_factory_name)'


steps:

- task: FileTransform@1
  inputs:
    folderPath: 'Swathi493/tf-asgmt1/parameter.json'
    fileType: 'json'
    targetFiles: 'parameter.json'
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'az-asgmts'
    backendAzureRmResourceGroupName: 'Devops-RG'
    backendAzureRmStorageAccountName: 'devopstrainingstorage'
    backendAzureRmContainerName: 'swathi-tfstate'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'az-asgmts'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'az-asgmts'
