# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/*.zip'
    fileType: 'json'
    targetFiles: 'parameters.json'
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'az-asgmts'
    backendAzureRmResourceGroupName: 'Devops-RG'
    backendAzureRmStorageAccountName: 'devopstrainingstorage'
    backendAzureRmContainerName: 'swathi-tfstate'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'az-asgmts'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'az-asgmts'
